spring.application.name: mcolc-web-backend

server:
  port: 8081

spring:
  security:
    oauth2:
      client:
        registration:
          nmo-skin:
            client-id: 1
            client-secret: MhaMqg93WiyxX7rOMn37M1kEl768yAPFA8rB2Lhr
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8080/login-success/nmo-skin"
            scope:
        provider:
          nmo-skin:
            authorization-uri: https://skin.nmo.net.cn/oauth/authorize
            token-uri: https://skin.nmo.net.cn/oauth/token
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/mcolc?serverTimezone=GMT%2B8&characterEncoding=utf-8&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true&allowMultiQueries=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: demo
    password:

