spring:
  application.name: mcolc-db-mq
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/mcolc?serverTimezone=GMT%2B8&characterEncoding=utf-8&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true&allowMultiQueries=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: demo
    password:
  rabbitmq:
    username: mcolc
    password: mcolc
    addresses: localhost:5672