spring:
  application.name: mcolc-db-mq
  data:
    mongodb:
      host: localhost
      port: 27017
      database: mcolc
  rabbitmq:
    username: mcolc
    password: mcolc
    addresses: localhost:5672