@startuml
'https://plantuml.com/class-diagram

'skin rose

rectangle EFK as e
rectangle "建表 SQL 语句" as a
rectangle cmdb_nl2sql as b


b -> e: 1. 将从查询中提取的实体名与已有实体名匹配相似度
b <-- e: 2. 按相似度返回实体名列表
b --> e: 3. 若有多个实体名则需要用户确认
e -> e: 4. 将用户确认结果与当前从查询中提取的实体名建立映射，并加入 EFK 系统中


e <-- a: 从建表 SQL 中提取实体名加入 EFK 系统中，并于该实体所在表的列名建立映射




@enduml